[build]
base = "."
publish = "docs/site"
command = """
pip3 install --user uv &&
export PATH=$PATH:$HOME/.local/bin &&
uv sync &&
uv pip install . &&
uv run --active --no-sync zensical build -f docs/az/mkdocs.yml --strict &&
uv run --active --no-sync zensical build -f docs/en/mkdocs.yml --strict &&
rm -rf docs/site &&
mkdir -p docs/site &&
cp -r docs/az/site/. docs/site/ &&
cp -r docs/en/site docs/site/en
"""
