import pytest
from httpx import Response


@pytest.fixture(scope='package')
def clopos_product_goods_with_variations_response():
    return Response(
        status_code=200,
        json={
            'success': True,
            'data': {
                'id': 419,
                'cid': None,
                'parent_id': None,
                'station_id': None,
                'category_id': None,
                'unit_id': 1,
                'net_output': 1,
                'type': 'GOODS',
                'name': 'Fanta',
                'parent_name': '',
                'image': None,
                'position': None,
                'barcode': None,
                'gov_code': '654564',
                'status': 1,
                'hidden': 0,
                'sold_by_weight': False,
                'max_age': None,
                'discountable': True,
                'giftable': False,
                'has_modifications': True,
                'meta': {
                    'langs': {'en': [], 'az': []},
                    'availability': {'schedules': {'itemAvailability': [], 'itemVisibility': []}},
                    'gov_package_code': '234234324',
                },
                'setting': None,
                'emenu_category_id': None,
                'emenu_position': None,
                'emenu_hidden': False,
                'accounting_category_id': None,
                'description': None,
                'price': 0,
                'cost_price': 0,
                'markup_rate': 0,
                'cooking_time': 0,
                'ignore_service_charge': False,
                'inventory_behavior': 0,
                'low_stock': 0,
                'unit_weight': 1,
                'created_at': '2024-07-01 07:51:25',
                'updated_at': '2024-07-01 08:01:04',
                'deleted_at': None,
                'name_slug': 'fanta',
                'full_name': 'Fanta',
                'gross_margin': 0,
                'slug': 'fanta',
                'color': '00bcd4',
                'is_inventory_behavior_changeable': True,
                'venues': [],
                'properties': [],
                'modifications': [
                    {
                        'id': 420,
                        'cid': None,
                        'parent_id': 419,
                        'station_id': None,
                        'category_id': None,
                        'unit_id': 1,
                        'net_output': 1,
                        'type': 'MODIFICATION',
                        'name': '0.5 L',
                        'parent_name': 'Fanta',
                        'image': None,
                        'position': None,
                        'barcode': None,
                        'gov_code': None,
                        'status': 1,
                        'hidden': 0,
                        'sold_by_weight': False,
                        'max_age': None,
                        'discountable': True,
                        'giftable': False,
                        'has_modifications': False,
                        'meta': {
                            'langs': {'en': [], 'az': []},
                            'gov_package_code': '234234324',
                        },
                        'setting': None,
                        'emenu_category_id': None,
                        'emenu_position': None,
                        'emenu_hidden': False,
                        'accounting_category_id': None,
                        'description': None,
                        'price': 5,
                        'cost_price': 1,
                        'markup_rate': 400,
                        'cooking_time': 0,
                        'ignore_service_charge': False,
                        'inventory_behavior': 0,
                        'low_stock': 0,
                        'unit_weight': 1,
                        'created_at': '2024-07-01 07:51:25',
                        'updated_at': '2025-08-22 12:19:43',
                        'deleted_at': None,
                        'name_slug': '05 l',
                        'full_name': 'Fanta 0.5 L',
                        'gross_margin': 80,
                        'slug': '05-l',
                        'venues': [],
                        'properties': [],
                    },
                    {
                        'id': 421,
                        'cid': None,
                        'parent_id': 419,
                        'station_id': None,
                        'category_id': None,
                        'unit_id': 1,
                        'net_output': 1,
                        'type': 'MODIFICATION',
                        'name': '1 L',
                        'parent_name': 'Fanta',
                        'image': None,
                        'position': None,
                        'barcode': None,
                        'gov_code': None,
                        'status': 1,
                        'hidden': 0,
                        'sold_by_weight': False,
                        'max_age': None,
                        'discountable': True,
                        'giftable': False,
                        'has_modifications': False,
                        'meta': {
                            'langs': {'en': [], 'az': []},
                            'gov_package_code': '234234324',
                        },
                        'setting': None,
                        'emenu_category_id': None,
                        'emenu_position': None,
                        'emenu_hidden': False,
                        'accounting_category_id': None,
                        'description': None,
                        'price': 10,
                        'cost_price': 7,
                        'markup_rate': 42.8571,
                        'cooking_time': 0,
                        'ignore_service_charge': False,
                        'inventory_behavior': 0,
                        'low_stock': 0,
                        'unit_weight': 1,
                        'created_at': '2024-07-01 07:51:26',
                        'updated_at': '2025-09-05 10:32:59',
                        'deleted_at': None,
                        'name_slug': '1 l',
                        'full_name': 'Fanta 1 L',
                        'gross_margin': 30,
                        'slug': '1-l',
                        'venues': [],
                        'properties': [],
                    },
                ],
                'taxes': [],
                'tags': [],
                'media': [],
            },
            'timestamp': '2025-09-05 10:32:59',
            'unix': 1662041699,
            'time': 100,
        },
    )


@pytest.fixture(scope='package')
def clopos_product_dish_with_modifiers():
    return Response(
        status_code=200,
        json={
            'success': True,
            'data': {
                'price': 200,
                'cost_price': 21.25,
                'id': 1,
                'cid': None,
                'parent_id': None,
                'station_id': 1,
                'category_id': 1,
                'unit_id': 1,
                'net_output': 1,
                'type': 'DISH',
                'name': 'Mega Wrap Combo with Free Raw Meatball Wrap.',
                'parent_name': '',
                'image': {
                    'original': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/original.jpg',
                    'extra_large': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/extra_large.jpg',
                    'original_large': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/original_large.jpg',
                    'thumb': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/thumb.jpg',
                    'blur_hash': 'LMSPb2j@~Xt7xvfQM{fQxuj[M{ay',
                },
                'position': 1,
                'barcode': '9780750310512',
                'gov_code': None,
                'status': 1,
                'hidden': 0,
                'sold_by_weight': False,
                'max_age': None,
                'discountable': True,
                'giftable': True,
                'has_modifications': False,
                'meta': {
                    'allergies': [],
                    'diets': [],
                    'langs': {
                        'en': {
                            'name': 'Mega Wrap Combo with Free Raw Meatball Wrap.',
                            'description': 'description test',
                        },
                        'az': {
                            'name': 'Mega Wrap Combo with Free Raw Meatball Wrap (AZ)',
                            'description': 'Sample description text (AZ)',
                        },
                        'ar': [],
                        'tr': [],
                        'ru': [],
                        'uz': [],
                        'kz': [],
                        'es': [],
                    },
                    'modifier_pos': {'5': 0, '8': 1, '9': 2, '32': 3},
                    'availability': {
                        'itemAvailability': False,
                        'itemVisibility': False,
                        'schedules': {'itemAvailability': [], 'itemVisibility': []},
                    },
                    'gov_package_code': '564564645',
                },
                'setting': None,
                'emenu_category_id': 1,
                'emenu_position': None,
                'emenu_hidden': False,
                'accounting_category_id': None,
                'description': None,
                'markup_rate': 561.157,
                'cooking_time': 20,
                'ignore_service_charge': False,
                'inventory_behavior': 0,
                'low_stock': 0,
                'unit_weight': 1,
                'created_at': '2024-05-15 12:36:10',
                'updated_at': '2025-09-25 06:26:22',
                'deleted_at': None,
                'name_slug': 'mega wrap combo with free raw meatball wrap',
                'full_name': 'Mega Wrap Combo with Free Raw Meatball Wrap.',
                'gross_margin': 89.375,
                'slug': 'mega-wrap-combo-with-free-raw-meatball-wrap',
                'color': '34495e',
                'venues': [],
                'properties': {'measure': 250, 'measure_unit_id': 5, 'stop_list_setting': []},
                'taxes': [
                    {
                        'id': 1,
                        'type_id': 2,
                        'rounding_option': 'ROUND_HALF_UP',
                        'priority': 1,
                        'calculation_type': 1,
                        'name': 'edv`',
                        'rate': 18,
                        'meta': None,
                        'is_default': False,
                        'status': 1,
                        'created_at': '2023-04-12T11:14:45.000000Z',
                        'deleted_at': None,
                        'type': {'id': 2, 'name': 'Daxil'},
                        'has_sale_types': True,
                        'sale_types': [
                            {
                                'id': 1004,
                                'name': 'test',
                                'media': [],
                                'pivot': {'tax_id': 1, 'sale_type_id': 1004},
                                'status': [],
                            },
                            {
                                'id': 2,
                                'name': 'Delivery',
                                'media': [
                                    {
                                        'urls': {
                                            'original': 'https://cdn.clopos.com/_clopos/delivery.png',
                                            'large': 'https://cdn.clopos.com/_clopos/delivery.png',
                                        }
                                    }
                                ],
                                'pivot': {'tax_id': 1, 'sale_type_id': 2},
                                'status': [],
                            },
                        ],
                    }
                ],
                'unit': {
                    'id': 1,
                    '_lft': 1,
                    '_rgt': 4,
                    'parent_id': None,
                    'name': 'piece',
                    'type': 'PIECE',
                    'symbol': 'pcs',
                    'equal': None,
                    'deleted_at': None,
                },
                'modificator_groups': [
                    {
                        'id': 5,
                        'name': 'Spice Selection',
                        'type': 1,
                        'min_select': 0,
                        'max_select': 1,
                        'meta': None,
                        'status': True,
                        'adjust_to_portion': False,
                        'created_at': '2024-05-15T12:36:10.000000Z',
                        'updated_at': '2024-05-18T11:47:10.000000Z',
                        'deleted_at': None,
                        'pivot': {'product_id': 1, 'modificator_group_id': 5},
                        'modificators': [
                            {
                                'id': 22,
                                'dish_id': 0,
                                'ingredient_id': None,
                                'group_id': 5,
                                'name': 'Medium Spice',
                                'image': None,
                                'price': 0,
                                'cost_price': 0,
                                'brutto': 0,
                                'default_count': 0,
                                'min_count': 0,
                                'max_count': 1,
                                'meta': None,
                                'status': True,
                                'position': 0,
                                'created_at': '2024-05-15T12:36:10.000000Z',
                                'updated_at': '2024-09-06T18:32:18.000000Z',
                                'deleted_at': None,
                                'media': [],
                                'ingredient': None,
                            },
                            {
                                'id': 23,
                                'dish_id': 0,
                                'ingredient_id': None,
                                'group_id': 5,
                                'name': 'Extra Spice',
                                'image': None,
                                'price': 0,
                                'cost_price': 0,
                                'brutto': 0,
                                'default_count': 0,
                                'min_count': 0,
                                'max_count': 1,
                                'meta': None,
                                'status': True,
                                'position': 1,
                                'created_at': '2024-05-15T12:36:10.000000Z',
                                'updated_at': '2024-09-06T18:32:18.000000Z',
                                'deleted_at': None,
                                'media': [],
                                'ingredient': None,
                            },
                            {
                                'id': 187,
                                'dish_id': 0,
                                'ingredient_id': 0,
                                'group_id': 5,
                                'name': 'yyy',
                                'image': None,
                                'price': 0,
                                'cost_price': 0,
                                'brutto': 0,
                                'default_count': 0,
                                'min_count': 0,
                                'max_count': 0,
                                'meta': None,
                                'status': True,
                                'position': 2,
                                'created_at': '2024-09-06T18:34:01.000000Z',
                                'updated_at': '2024-09-06T18:35:09.000000Z',
                                'deleted_at': None,
                                'media': [],
                                'ingredient': None,
                            },
                        ],
                    }
                ],
                'recipe': [
                    {
                        'id': 233,
                        'cid': None,
                        'parent_id': None,
                        'station_id': None,
                        'category_id': None,
                        'unit_id': 1,
                        'net_output': 1,
                        'type': 'PREPARATION',
                        'name': 'Quzu Y/F',
                        'parent_name': '',
                        'image': None,
                        'position': None,
                        'barcode': None,
                        'gov_code': None,
                        'status': 1,
                        'hidden': 0,
                        'sold_by_weight': False,
                        'max_age': None,
                        'discountable': True,
                        'giftable': False,
                        'has_modifications': False,
                        'meta': None,
                        'setting': None,
                        'emenu_category_id': None,
                        'emenu_position': None,
                        'emenu_hidden': False,
                        'accounting_category_id': None,
                        'description': None,
                        'price': 0,
                        'cost_price': 5,
                        'markup_rate': 0,
                        'cooking_time': 0,
                        'ignore_service_charge': False,
                        'inventory_behavior': 0,
                        'low_stock': 0,
                        'unit_weight': 0,
                        'created_at': '2024-05-20 14:08:30',
                        'updated_at': '2024-08-30 12:15:27',
                        'deleted_at': None,
                        'name_slug': 'quzu yf',
                        'full_name': 'Quzu Y/F',
                        'gross_margin': 0,
                        'slug': 'quzu-yf',
                        'pivot': {
                            'dish_id': 1,
                            'ingredient_id': 233,
                            'net': '0.000',
                            'gross': '1.000',
                            'net_put': None,
                        },
                        'properties': [],
                        'unit': {
                            'id': 1,
                            '_lft': 1,
                            '_rgt': 4,
                            'parent_id': None,
                            'name': 'piece',
                            'type': 'PIECE',
                            'symbol': 'pcs',
                            'equal': None,
                            'deleted_at': None,
                        },
                    }
                ],
                'tags': [],
                'media': [
                    {
                        'uuid': 'f78e74e9-75da-468f-b7cf-96bed863832f',
                        'mime_type': 'image/jpeg',
                        'size': 152789,
                        'urls': {
                            'original': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/original.jpg',
                            'extra_large': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/extra_large.jpg',
                            'original_large': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/original_large.jpg',
                            'thumb': 'https://cdn.clopos.com/omega/f78e74e9-75da-468f-b7cf-96bed863832f/thumb.jpg',
                        },
                        'blur_hash': 'LMSPb2j@~Xt7xvfQM{fQxuj[M{ay',
                        'dimensions': {'width': 1373, 'height': 776},
                    }
                ],
            },
            'timestamp': '2025-09-05 10:32:59',
            'unix': 1662041699,
            'time': 100,
        },
    )


@pytest.fixture(scope='package')
def clopos_product_timer_response():
    return Response(
        status_code=200,
        json={
            'success': True,
            'data': {
                'id': 407,
                'cid': None,
                'parent_id': None,
                'station_id': None,
                'category_id': 41,
                'unit_id': 1,
                'net_output': 1,
                'type': 'TIMER',
                'name': 'PS5',
                'parent_name': '',
                'image': None,
                'position': 0,
                'barcode': None,
                'gov_code': None,
                'status': 1,
                'hidden': 0,
                'sold_by_weight': False,
                'max_age': None,
                'discountable': True,
                'giftable': False,
                'has_modifications': False,
                'meta': None,
                'setting': {
                    'calculation_methods': 0,
                    'interval': 60,
                    'prices': [{'price': 3, 'from': 120}],
                },
                'emenu_category_id': 0,
                'emenu_position': 0,
                'emenu_hidden': False,
                'accounting_category_id': None,
                'description': None,
                'price': 10,
                'cost_price': 0,
                'markup_rate': 0,
                'cooking_time': 0,
                'ignore_service_charge': False,
                'inventory_behavior': 3,
                'low_stock': 0,
                'unit_weight': 1,
                'created_at': '2024-06-06 06:43:42',
                'updated_at': '2024-07-22 08:16:40',
                'deleted_at': None,
                'name_slug': 'ps5',
                'full_name': 'PS5',
                'gross_margin': 100,
                'slug': 'ps5',
                'color': '00bcd4',
                'venues': [],
                'properties': [],
                'taxes': [
                    {
                        'id': 5,
                        'type_id': 3,
                        'rounding_option': 'ROUND_HALF_UP',
                        'priority': 1,
                        'calculation_type': 1,
                        'name': 'Simplified Tax 2%',
                        'rate': 6.95,
                        'meta': None,
                        'is_default': False,
                        'status': 1,
                        'created_at': '2023-07-24T23:49:53.000000Z',
                        'deleted_at': None,
                        'type': {'id': 3, 'name': 'Sabit vergi'},
                        'has_sale_types': False,
                        'sale_types': [],
                    }
                ],
                'tags': [],
                'media': [],
            },
            'timestamp': '2025-09-05 10:32:59',
            'unix': 1662041699,
            'time': 100,
        },
    )
