name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/integrify/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install build dependencies
        run: pip install build
      - name: Build distribution
        run: python -m build
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
